version: '3'
services: 
   web:
    build: 
      content: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      content: .
      dockerfile: Dockerfile.dev
      ports:
        - "3000:3000"
      voulmes:
        - /app/node_modules
        - .:/app
      command: ["npm", "run", "test"]

